### ISSUE TITLE
Deadlock !Deadlock !

### ISSUE THREAD

**Issue by liuj-fnst** [javaee/glassfish#21768]
when Server is starting, Deadlock will occurs sometimes
Found one Java-level deadlock:

"Timer-21":
waiting to lock monitor 0x31ceb894 (object 0x247b1028, a java.lang.Class),
which is held by "pool-1-thread-11"
"pool-1-thread-11":
waiting to lock monitor 0x31efa42c (object 0x0f1f3d00, a com.sun.enterprise.util.ConnectorClassLoader),
which is held by "pool-1-thread-6"
"pool-1-thread-6":
waiting to lock monitor 0x31c0994c (object 0x0efa0458, a com.sun.appserv.server.util.ASURLClassLoader),
which is held by "pool-1-thread-11"

Java stack information for the threads listed above:

"Timer-21":
at java.util.logging.Logger.getLogger(Logger.java:321)

waiting to lock <0x247b1028> (a java.lang.Class for java.util.logging.Logger)
at com.sun.jmx.trace.TraceManager.getLogger(TraceManager.java:176)
at com.sun.jmx.trace.TraceManager.isSelected(TraceManager.java:197)
at com.sun.jmx.trace.Trace.isSelected(Trace.java:89)
at javax.management.timer.Timer.isTraceOn(Timer.java:116)
at javax.management.timer.Timer.sendNotification(Timer.java:1222)
at javax.management.timer.Timer.notifyAlarmClock(Timer.java:1206)
at javax.management.timer.TimerAlarmClock.run(Timer.java:1289)
at java.util.TimerThread.mainLoop(Timer.java:512)
at java.util.TimerThread.run(Timer.java:462)
"pool-1-thread-11":
at com.sun.enterprise.util.ConnectorClassLoader.loadClass(ConnectorClassLoader.java:182)
waiting to lock <0x0f1f3d00> (a com.sun.enterprise.util.ConnectorClassLoader)
at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1482)
at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2289)
at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1364)
at java.util.ResourceBundle.findBundle(ResourceBundle.java:1328)
at java.util.ResourceBundle.findBundle(ResourceBundle.java:1282)
at java.util.ResourceBundle.findBundle(ResourceBundle.java:1282)
at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1224)
at java.util.ResourceBundle.getBundle(ResourceBundle.java:952)
at java.util.logging.Logger.findResourceBundle(Logger.java:1332)
locked <0x05080888> (a java.util.logging.Logger)
at java.util.logging.Logger.setupResourceInfo(Logger.java:1386)
locked <0x05080888> (a java.util.logging.Logger)
at java.util.logging.Logger.getLogger(Logger.java:367)
locked <0x247b1028> (a java.lang.Class for java.util.logging.Logger)
at com.sun.enterprise.server.logging.BaseLogManager.doInitializeLogger(BaseLogManager.java:125)
at com.sun.enterprise.server.logging.BaseLogManager.addLogger(BaseLogManager.java:196)
locked <0x0efa05b8> (a java.util.ArrayList)
at java.util.logging.LogManager.demandLogger(LogManager.java:381)
at java.util.logging.Logger.demandLogger(Logger.java:290)
at java.util.logging.Logger.getLogger(Logger.java:321)
locked <0x247b1028> (a java.lang.Class for java.util.logging.Logger)
at java.util.jar.Attributes.read(Attributes.java:405)
at java.util.jar.Manifest.read(Manifest.java:232)
at java.util.jar.Manifest.(Manifest.java:50)
at java.util.jar.JarFile.getManifestFromReference(JarFile.java:163)
at java.util.jar.JarFile.getManifest(JarFile.java:149)
at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:696)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:228)
at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
locked <0x0efa0458> (a com.sun.appserv.server.util.ASURLClassLoader)
at com.sun.appserv.server.util.ASURLClassLoader.loadClass(ASURLClassLoader.java:144)
at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
at my.servlet1.init(servlet1.java:31)
at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1100)
locked <0x0fff7dd8> (a org.apache.catalina.core.StandardWrapper)
at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1023)
locked <0x0fff7dd8> (a org.apache.catalina.core.StandardWrapper)
at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4969)
at org.apache.catalina.core.StandardContext.start(StandardContext.java:5376)
locked <0x0fe3b7d0> (a com.sun.enterprise.web.WebModule)
at com.sun.enterprise.web.WebModule.start(WebModule.java:345)
locked <0x0fe3b7d0> (a com.sun.enterprise.web.WebModule)
at com.sun.enterprise.web.LifecycleStarter.doRun(LifecycleStarter.java:58)
at com.sun.appserv.management.util.misc.RunnableBase.runSync(RunnableBase.java:304)
at com.sun.appserv.management.util.misc.RunnableBase.run(RunnableBase.java:341)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
at java.lang.Thread.run(Thread.java:662)
"pool-1-thread-6":
at java.lang.ClassLoader.loadClass(ClassLoader.java:291)
waiting to lock <0x0efa0458> (a com.sun.appserv.server.util.ASURLClassLoader)
at com.sun.appserv.server.util.ASURLClassLoader.loadClass(ASURLClassLoader.java:144)
at java.lang.ClassLoader.loadClass(ClassLoader.java:295)
locked <0x0f1f3158> (a java.net.URLClassLoader)
at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
at com.sun.enterprise.util.ConnectorClassLoader.loadClass(ConnectorClassLoader.java:187)
locked <0x0f1f3d00> (a com.sun.enterprise.util.ConnectorClassLoader)
at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1482)
at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:251)
at org.apache.catalina.core.ApplicationFilterConfig.setFilterDef(ApplicationFilterConfig.java:385)
at org.apache.catalina.core.ApplicationFilterConfig.(ApplicationFilterConfig.java:119)
at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4521)
locked <0x0fe4bc80> (a java.util.HashMap)
at org.apache.catalina.core.StandardContext.start(StandardContext.java:5369)
locked <0x0fe3bbd0> (a com.sun.enterprise.web.WebModule)
at com.sun.enterprise.web.WebModule.start(WebModule.java:345)
locked <0x0fe3bbd0> (a com.sun.enterprise.web.WebModule)
at com.sun.enterprise.web.LifecycleStarter.doRun(LifecycleStarter.java:58)
at com.sun.appserv.management.util.misc.RunnableBase.runSync(RunnableBase.java:304)
at com.sun.appserv.management.util.misc.RunnableBase.run(RunnableBase.java:341)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
at java.lang.Thread.run(Thread.java:662)
Found 1 deadlock.

In the following cases,

deploy many WEB apllications(A,B),and
2）WEB application(A) defined servlet that executed in starting time.eg init method，load-on-startup），and
3）the filter is defined in the WEB application(B)，and
4）the Jar  that includes the servlet class is defined in Cluster's classpath suffix in WEB application(A)，and
5）the filter class puts in WEB—INF in in WEB application(B)， and
6）another Jar’s（Y）class is referenced by WEB application(A) also defineds in Server's classpath suffix
7）when the servlet of WEB application(A) is initialized，In the processing of the JDK will output log.※１
※１ this is due to the referenced Jar‘s（Y）MANIFEST.MF that definition is error（Repeat definition） results in outting the ’warning log'.
reason:

1)In the WEB application (A)’s servletini processing, it began to load the Jar (Y) class from ASURLClassLoade,
at this point, the ASURLClassLoader is locked.
2）In the WEB application (B)’s filter processing, due to the delegation mechanism,
it retrievals class from ConnectorClassLoader through WebappClassLoader. At this point, the ConnectorClassLoader is locked.
3）The MANIFEST. MF’s definition in the Web application (A)’s the Jar (Y) is wrong,
lead to the JDK output warning messages, it began to retrieval class from ConnectorClassLoader through WebappClassLoader,making use of the current.
4）In the WEB application (B)’s filter processing, due to the delegation mechanism,
it retrievals class from ASURLClassLoader through ConnectorClassLoader .

so,ASURLClassLoader and ConnectorClassLoader are LOCKED by different threads，then，the deadlock occurs.

I provide examples (Sample.zip\APP) and Source (Sample.zip\Source), as well as reproduction methods (Sample.zip\readme.txt).
That's all.Thanks.

**Comment by liuj-fnst** [comment]
U can download the Smaple.zip in : https://github.com/javaee/glassfish/issues/21628

**Comment by sivakumart** [comment]
@liuj-fnst: Hello, could you please expand on your usecase is? 

Since GF3.0, the use of classpath-prefix and classpath-suffix has been removed, and marked as "do not use" in the admin GUI. Please see page 25 of the GF 4.1 release notes https://javaee.github.io/glassfish/doc/4.0/release-notes.pdf for more information.

If you would like Jar1.jar and Jar2.jar to be used as additional libraries to be placed on the classpath of an application, please consider using "--libraries" option while deploying your WEBA.war https://docs.oracle.com/cd/E18930_01/html/821-2433/deploy-1.html#SJSASEEREFMANdeploy-1 (ref: https://docs.oracle.com/cd/E18930_01/html/821-2418/gatej.html#scrolltoc) as follows:
`
$ asadmin deploy --target  cluster1 --libraries ./Sample/App/Jar1.jar,./Sample/App/Jar2.jar ./Sample/App/WEBA.war
`
Since I haven't understood your usecase scenario well, I deployed WEBA.war and WEBB.war using Jar1.jar and Jar2.jar as per-application libraries as shown above, and the clustered server instance started fine with no deadlocks.

For a detailed explanation on how classloaders work in GlassFish and how applications can be developed and deployed to leverage this, please see https://docs.oracle.com/cd/E18930_01/html/821-2418/beade.html#scrolltoc

Marking this issue as closed for now. If you still get a deadlock after fixing your application deployment to match this, please reopen this issue or open a new issue. Thanks.
