### ISSUE TITLE
Regression in secure admin

### ISSUE THREAD

**Issue by yaminikb** [javaee/glassfish#21764]
We have run into a regression in secure admin recently. However, we are not sure about the exact date when this feature broke.

After enabling secure admin (enable-secure-admin) and restarting the server, admin console is inaccessible. The following exception is logged in the server.log:

GRIZZLY0013: Exception during FilterChain execution
java.lang.NullPointerException
   at org.glassfish.grizzly.portunif.BackChannelFilter.handleWrite(BackChannelFilter.java:111)
   at org.glassfish.grizzly.filterchain.ExecutorResolver$8.execute(ExecutorResolver.java:111)
   at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
   at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
   at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
   at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
   at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
   at org.glassfish.grizzly.filterchain.DefaultFilterChain.write(DefaultFilterChain.java:397)
   at org.glassfish.grizzly.http2.Http2ConnectionOutputSink.writeDownStream(Http2ConnectionOutputSink.java:134)
   at org.glassfish.grizzly.http2.Http2ConnectionOutputSink.writeDataDownStream(Http2ConnectionOutputSink.java:190)
   at org.glassfish.grizzly.http2.DefaultOutputSink.flushToConnectionOutputSink(DefaultOutputSink.java:503)
   at org.glassfish.grizzly.http2.DefaultOutputSink.writeEmptyFin(DefaultOutputSink.java:569)
   at org.glassfish.grizzly.http2.DefaultOutputSink.close(DefaultOutputSink.java:521)
   at org.glassfish.grizzly.http2.Http2Stream.onProcessingComplete(Http2Stream.java:455)
   at org.glassfish.grizzly.http2.Http2ServerFilter.handleEvent(Http2ServerFilter.java:575)
   at org.glassfish.grizzly.filterchain.ExecutorResolver$6.execute(ExecutorResolver.java:94)
   at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
   at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
   at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
   at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
   at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
   at org.glassfish.grizzly.filterchain.FilterChainContext.notifyDownstream(FilterChainContext.java:952)
   at org.glassfish.grizzly.filterchain.FilterChainContext.notifyDownstream(FilterChainContext.java:934)
   at org.glassfish.grizzly.http.io.OutputBuffer.endRequest(OutputBuffer.java:397)
   at org.glassfish.grizzly.http.server.Response.finish(Response.java:517)
   at org.glassfish.grizzly.http.server.HttpServerFilter.afterService(HttpServerFilter.java:384)
   at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:290)
   at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
   at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
   at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
   at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
   at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
   at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
   at org.glassfish.grizzly.filterchain.FilterChainContext$1.run(FilterChainContext.java:202)
   at org.glassfish.grizzly.filterchain.FilterChainContext.resume(FilterChainContext.java:226)
   at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:242)
   at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
   at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
   at java.lang.Thread.run(Thread.java:748)
]]

This exception is seen even when accessing the console from the local machine.

**Comment by rlubke** [comment]
Workaround:  After enabling secure admin, change to the protocol value of the secure admin network listener from pu-protocol to sec-admin-listener.  

This means you won't be automatically redirected if you attempt access the admin console via http vs https.

**Comment by rlubke** [comment]
I've logged: https://github.com/javaee/grizzly/issues/1933

**Comment by rlubke** [comment]
In short, the problem is that HTTP/2 is incompatible with the current implementation of port unification.

Port unification in 2.4.x assumes a protocol is a request/response protocol like HTTP/1.1.  However, HTTP/2, while at the user level, appears similar, frames can be exchanged on the session that aren't a part of an HTTP request.  When this occurs, the NPE emerges.

Port unification in Grizzly 3.0 (not yet released) has been changed to address this some time back, but Grizzly 3.0 is not a drop-in replacement for Grizzly 2.4.x - it has major API changes that aren't compatible with the code currently in GlassFish.  As such, integrating Grizzly 3.0 isn't an option.

Back-porting the necessary port unification changes from 3.0 back to 2.4.x would reduce the incompatible changes, but there would still be several conflicts that could cause pain for other components that rely on Grizzly.

Based on these factors, I think the correct course of action is to disable HTTP/2 when port unification is in use (as is the case with the secure-admin feature).  This impacts **only** the listeners leveraging unification.   HTTP/2 can still be used properly with non-unified listeners.

**Comment by edburns** [comment]
> Based on these factors, I think the correct course of action is to disable HTTP/2 when port unification is in use (as is the case with the secure-admin feature). This impacts only the listeners leveraging unification. HTTP/2 can still be used properly with non-unified listeners.

This seems like the most appropriate course of action considering product plans and goals.
