### ISSUE TITLE
Error unregistering ProbeProvider

### ISSUE THREAD

**Issue by glassfishusr** [javaee/glassfish#21915]
I get the error below when shutting down glassfish.

[2017-06-22T16:46:34.993-0400] [glassfish 5.0] [INFO] [NCLS-JMX-00001] [javax.enterprise.system.jmx] [tid: _ThreadID=115 _ThreadName=Thread-34] [timeMillis: 1498164394993] [levelValue: 800] [[
  JMXStartupService and JMXConnectors have been shut down.]]

[2017-06-22T16:46:35.023-0400] [glassfish 5.0] [WARNING] [NCLS-MON-00506] [javax.enterprise.system.tools.monitor] [tid: _ThreadID=122 _ThreadName=RunLevelControllerThread-1498164395008] [timeMillis: 1498164395023] [levelValue: 900] [[
  Error unregistering ProbeProvider
java.lang.NullPointerException
	at org.glassfish.flashlight.impl.provider.FlashlightProbeProviderFactory.unregisterProbeProvider(FlashlightProbeProviderFactory.java:376)
	at com.sun.ejb.containers.util.pool.AbstractPool.unregisterProbeProvider(AbstractPool.java:566)
	at com.sun.ejb.containers.util.pool.NonBlockingPool.close(NonBlockingPool.java:429)
	at com.sun.ejb.containers.StatelessSessionContainer.doConcreteContainerShutdown(StatelessSessionContainer.java:679)
	at com.sun.ejb.containers.BaseContainer.onShutdown(BaseContainer.java:4290)
	at org.glassfish.ejb.startup.EjbApplication.stop(EjbApplication.java:299)
	at org.glassfish.internal.data.EngineRef.stop(EngineRef.java:161)
	at org.glassfish.internal.data.ModuleInfo.stop(ModuleInfo.java:324)
	at org.glassfish.internal.data.ApplicationInfo.stop(ApplicationInfo.java:380)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.unload(ApplicationLifecycle.java:1059)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.disable(ApplicationLifecycle.java:2127)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.disable(ApplicationLifecycle.java:113)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.stopApplication(ApplicationLoaderService.java:496)
	at com.sun.enterprise.v3.server.ApplicationLoaderService.preDestroy(ApplicationLoaderService.java:464)
	at org.jvnet.hk2.internal.ClazzCreator.preDestroyMe(ClazzCreator.java:340)
	at org.jvnet.hk2.internal.ClazzCreator.dispose(ClazzCreator.java:405)
	at org.jvnet.hk2.internal.SystemDescriptor.dispose(SystemDescriptor.java:542)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.destroyOne(AsyncRunLevelContext.java:427)
	at org.glassfish.hk2.runlevel.RunLevelContext.destroyOne(RunLevelContext.java:101)
	at org.jvnet.hk2.internal.ServiceHandleImpl.destroy(ServiceHandleImpl.java:183)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$DownQueueRunner.run(CurrentTaskFuture.java:1294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

## Environment Details
* GlassFish Version (and build number): Version 5 build 6
* JDK version: 1.8.0_131-b11
* OS: Windows 7 64 bits
* Database:Oracle, MySQL, DB2

----------

## Problem Description
The above stack trace is logged to the log file when glassfish is shutdown. The error occurs every time whether an application is deployed or not. The error can be easily reproduce by shutting down glassfish from either the command line with asadmin stop-domain or from within Netbeans.

It seems like the error can be ignore since the server does shutdown. However, I would not upgrade glassfish in production to version 5 build 6 with the above error.

**Comment by srinivaskrishnan** [comment]
Not able to reproduce. Still working on trying to reproduce,

**Comment by srinivaskrishnan** [comment]
Requesting the filer to attach the application with which we can reproduce the issue. Thanks.

**Comment by srinivaskrishnan** [comment]
gf-remote-queue - Build # 119 - Successful:

Check console output at http://sca00kou.us.oracle.com:8080//job/gf-remote-queue/119 to view the results.

**Comment by glassfishusr** [comment]
Hi Srinivas,


The error occurs when there is a JEE application deploy. It can be any application, simple or complex. I've attached a simple NetBeans Hello JEE application that has a simple HTML page, an EJB, and a Web Service. When there is an application deploy on GlassFish and the server is shutdown, the error below occurs.


Info:   Server shutdown initiated
Info:   Unregistered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishImpl@1ab6718 from service registry.
Info:   FileMonitoring shutdown
Info:   JMXStartupService: Stopped JMXConnectorServer: null
Info:   JMXStartupService and JMXConnectors have been shut down.
Warning:   Error unregistering ProbeProvider
java.lang.NullPointerException
 at org.glassfish.flashlight.impl.provider.FlashlightProbeProviderFactory.unregisterProbeProvider(FlashlightProbeProviderFactory.java:376)
 at com.sun.ejb.containers.util.pool.AbstractPool.unregisterProbeProvider(AbstractPool.java:566)
 at com.sun.ejb.containers.util.pool.NonBlockingPool.close(NonBlockingPool.java:429)
 at com.sun.ejb.containers.StatelessSessionContainer.doConcreteContainerShutdown(StatelessSessionContainer.java:679)
 at com.sun.ejb.containers.BaseContainer.onShutdown(BaseContainer.java:4290)
 at org.glassfish.ejb.startup.EjbApplication.stop(EjbApplication.java:299)
 at org.glassfish.internal.data.EngineRef.stop(EngineRef.java:161)
 at org.glassfish.internal.data.ModuleInfo.stop(ModuleInfo.java:324)
 at org.glassfish.internal.data.ApplicationInfo.stop(ApplicationInfo.java:380)
 at com.sun.enterprise.v3.server.ApplicationLifecycle.unload(ApplicationLifecycle.java:1059)
 at com.sun.enterprise.v3.server.ApplicationLifecycle.disable(ApplicationLifecycle.java:2127)
 at com.sun.enterprise.v3.server.ApplicationLifecycle.disable(ApplicationLifecycle.java:113)
 at com.sun.enterprise.v3.server.ApplicationLoaderService.stopApplication(ApplicationLoaderService.java:496)
 at com.sun.enterprise.v3.server.ApplicationLoaderService.preDestroy(ApplicationLoaderService.java:464)
 at org.jvnet.hk2.internal.ClazzCreator.preDestroyMe(ClazzCreator.java:340)
 at org.jvnet.hk2.internal.ClazzCreator.dispose(ClazzCreator.java:405)
 at org.jvnet.hk2.internal.SystemDescriptor.dispose(SystemDescriptor.java:542)
 at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.destroyOne(AsyncRunLevelContext.java:427)
 at org.glassfish.hk2.runlevel.RunLevelContext.destroyOne(RunLevelContext.java:101)
 at org.jvnet.hk2.internal.ServiceHandleImpl.destroy(ServiceHandleImpl.java:183)
 at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$DownQueueRunner.run(CurrentTaskFuture.java:1294)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:748)

Warning:   Error unregistering ProbeProvider
java.lang.NullPointerException
 at org.glassfish.flashlight.impl.provider.FlashlightProbeProviderFactory.unregisterProbeProvider(FlashlightProbeProviderFactory.java:376)
 at com.sun.ejb.containers.BaseContainer.unregisterProbeListeners(BaseContainer.java:4462)
 at com.sun.ejb.containers.BaseContainer.doContainerCleanup(BaseContainer.java:4433)
 at com.sun.ejb.containers.BaseContainer.onShutdown(BaseContainer.java:4293)
 at org.glassfish.ejb.startup.EjbApplication.stop(EjbApplication.java:299)
 at org.glassfish.internal.data.EngineRef.stop(EngineRef.java:161)
 at org.glassfish.internal.data.ModuleInfo.stop(ModuleInfo.java:324)
 at org.glassfish.internal.data.ApplicationInfo.stop(ApplicationInfo.java:380)
 at com.sun.enterprise.v3.server.ApplicationLifecycle.unload(ApplicationLifecycle.java:1059)
 at com.sun.enterprise.v3.server.ApplicationLifecycle.disable(ApplicationLifecycle.java:2127)
 at com.sun.enterprise.v3.server.ApplicationLifecycle.disable(ApplicationLifecycle.java:113)
 at com.sun.enterprise.v3.server.ApplicationLoaderService.stopApplication(ApplicationLoaderService.java:496)
 at com.sun.enterprise.v3.server.ApplicationLoaderService.preDestroy(ApplicationLoaderService.java:464)
 at org.jvnet.hk2.internal.ClazzCreator.preDestroyMe(ClazzCreator.java:340)
 at org.jvnet.hk2.internal.ClazzCreator.dispose(ClazzCreator.java:405)
 at org.jvnet.hk2.internal.SystemDescriptor.dispose(SystemDescriptor.java:542)
 at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.destroyOne(AsyncRunLevelContext.java:427)
 at org.glassfish.hk2.runlevel.RunLevelContext.destroyOne(RunLevelContext.java:101)
 at org.jvnet.hk2.internal.ServiceHandleImpl.destroy(ServiceHandleImpl.java:183)
 at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$DownQueueRunner.run(CurrentTaskFuture.java:1294)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:748)



Thanks,


Juan



________________________________

**Comment by srinivaskrishnan** [comment]
Able to reproduce.

**Comment by glassfishusr** [comment]
Do you know what causes the error?


________________________________

**Comment by srinivaskrishnan** [comment]
CI Test Run successfully. Fixed the issue.

**Comment by yaminikb** [comment]
Fixed

**Comment by glassfishusr** [comment]
Which release is the fix in?


________________________________
