### ISSUE TITLE
When select Cipher Suites the log say "CipherSuites may not be null"

### ISSUE THREAD

**Issue by cgomeznt** [javaee/glassfish#22231]
# "When select Cipher Suites the log say "CipherSuites may not be null""

## Environment Details
* GlassFish Version (Open Source Edition 3.0.1 (build 22)):
* JDK version: "1.6.0_36" - OpenJDK Runtime Environment (IcedTea6 1.13.8) (rhel-1.13.8.1.el6_7-x86_64) -
 OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
* OS: Centos 6 - 2.6.32-573.3.1.el6.centos.plus.x86_64
* Database:

----------

## Problem Description
[//]: # "When we go to GUI Configuration > Network Config > admin-listener  > SSL and choose all or only one cipher suite, produce the next error 
[#|2017-08-18T17:32:47.955-0400|SEVERE|oracle-glassfish3.0.1|com.sun.grizzly.config.GrizzlyServiceListener|_ThreadID=30;_ThreadName=Thread-1;|ProtocolChain exception "
# "Is easy to reproduce"
# "stack traces of the log

[#|2017-08-18T17:32:47.955-0400|SEVERE|oracle-glassfish3.0.1|com.sun.grizzly.config.GrizzlyServiceListener|_ThreadID=30;_ThreadName=Thread-1;|ProtocolChain exception
java.lang.IllegalArgumentException: CipherSuites may not be null
        at sun.security.ssl.CipherSuiteList.<init>(CipherSuiteList.java:78)
        at sun.security.ssl.SSLEngineImpl.setEnabledCipherSuites(SSLEngineImpl.java:1776)
        at com.sun.grizzly.filter.SSLReadFilter.newSSLEngine(SSLReadFilter.java:358)
        at com.sun.grizzly.filter.SSLReadFilter.obtainSSLEngine(SSLReadFilter.java:394)
        at com.sun.grizzly.filter.SSLReadFilter.execute(SSLReadFilter.java:154)
        at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:135)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:102)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:88)
        at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:76)
        at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:53)
        at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:57)
        at com.sun.grizzly.ContextTask.run(ContextTask.java:69)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:330)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:309)
        at java.lang.Thread.run(Thread.java:701)"

## Steps to reproduce
# "Step by step instructions to reproduce the problem

Go to GUI Configuration > Network Config > admin-listener  > General and Enable the check Security and save.
Then go to Configuration > Network Config > admin-listener  > SSL and fill 
Certificate NickName:
Key Store:
Trust Store:
save an restart de service.
Then go again to Configuration > Network Config > admin-listener  > SSL and choose all or only one cipher suite, produce error, you can see the error in the log server.log"
[//]: # "Provide sample code/application if relevant"

## Impact of Issue
# "Very Important for the PCI rules https://www.pcisecuritystandards.org/"

# "High"

**Comment by yaminikb** [comment]
@cgomeznt Have you tried on latest GlassFish 5.0?
http://download.oracle.com/glassfish/5.0/nightly/index.html

**Comment by cgomeznt** [comment]
NO, because the server is now in Production and need first activete de SSL.

**Comment by yaminikb** [comment]
@cgomeznt Please go through the support channel for getting fix/patch on GlassFish 3.0.1

**Comment by cgomeznt** [comment]
Thanks @yaminikb , can you give me the url of fix/patch on GlassFish 3.0.1?

**Comment by cgomeznt** [comment]
@yaminikb, we tried with GlassFish 4.0 and GlassFish 5.0 was fine.
With GlassFish 3.0.1 nothing yet. When we execute 
asadmin list-supported-cipher-suites
     java.net.SocketException: Unexpected end of file from server
     Command list-supported-cipher-suites failed.

**Comment by cgomeznt** [comment]
Can i say this is a Bug??

**Comment by delabassee** [comment]
@cgomeznt GF 3.0.1 is +7 years old! Oracle provides commercial support for Oracle GlassFish server 3.x (extended support until end 2017).; just contact your local Oracle sales office. A free alternative solution is to upgrade to a more recent GF version.

**Comment by cgomeznt** [comment]
Hi, can´t solved with Glassfish, but we used a Apache ProxyPass and Apache respond the front with the correct cipher
